# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

True

### 2. Create a random tensor with shape `(7, 7)`.


In [13]:
# Import torch
import torch

# Create random tensor
tensor_2 = torch.randn([7,7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor
tensor_3 = torch.rand(1,7)
print(tensor_3.shape)
# Perform matrix multiplication 

torch.matmul(tensor_2, tensor_3.T)


torch.Size([1, 7])


tensor([[-0.3439],
        [ 0.5543],
        [ 0.2091],
        [ 0.6098],
        [ 1.2262],
        [-2.9150],
        [-0.7588]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [25]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
tensor_3_set = torch.rand(7,7)
tensor_2_set = torch.randn([1,7])


# Matrix multiply tensors
torch.matmul(tensor_2_set, tensor_3_set)


tensor([[-1.8430, -0.1575, -3.2904, -1.1780, -1.9017, -0.3582, -0.7017]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [27]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [55]:
# Set random seed
torch.manual_seed(1234)
torch.mps.manual_seed(1234)

# Check for access to GPU
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(device)

# Create two random tensors on GPU
tensor_1 = torch.randn([2,3],device=device)
tensor_2 = torch.randn([2,3],device=device)

tensor_1, tensor_2


mps


(tensor([[-0.0516,  0.7090,  0.9474],
         [ 0.8520,  0.3647, -1.5575]], device='mps:0'),
 tensor([[-2.0092,  2.2507, -0.6096],
         [ 1.3548,  0.7295,  1.2154]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [57]:
# Perform matmul on tensor_A and tensor_B

output = torch.matmul(tensor_1, tensor_2.T)
output

tensor([[ 1.1220,  1.5989],
        [ 0.0583, -0.4727]], device='mps:0')

### 8. Find the maximum and minimum values of the output of 7.

In [59]:
# Find max
torch.max(output)

# Find min
torch.min(output)


tensor(-0.4727, device='mps:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [68]:
# Find arg max
print(torch.argmax(output))


# Find arg min
print(torch.argmin(output))


tensor(1, device='mps:0')
tensor(3, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [72]:
# Set seed


# Create random tensor
tensor = torch.randn(1,1,1,10)


# Remove single dimensions
tensor_2 = torch.squeeze(tensor)


# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_2, tensor_2.shape)


tensor([[[[ 0.8042, -0.1383,  0.3196, -1.0187, -1.3147,  2.5228,  0.4501,
            0.2709, -0.8087, -0.0217]]]]) torch.Size([1, 1, 1, 10])
tensor([ 0.8042, -0.1383,  0.3196, -1.0187, -1.3147,  2.5228,  0.4501,  0.2709,
        -0.8087, -0.0217]) torch.Size([10])
